version: '3.4'

services:
  testapi:
    container_name: testapi
    build:
        context: .
        dockerfile: TestAPI/Dockerfile
    ports:
        - "5000:80"
    depends_on: [ db ]

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql_db
    environment:
        SA_PASSWORD: "TestAPI12345"
        ACCEPT_EULA: "Y"
    ports:
        - "6000:1433"